name: Deploy Frontend to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Install frontend dependencies
      - name: Install Client Dependencies
        working-directory: ./client
        run: npm install

      # Build frontend
      - name: Build Client
        working-directory: ./client
        run: npm run build
        env:
          VITE_SERVER_URI: ${{ secrets.VITE_SERVER_URI }}
          VITE_GUEST_USER: ${{ secrets.VITE_GUEST_USER }}
          VITE_GUEST_PWD: ${{ secrets.VITE_GUEST_PWD }}

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Deploy dist folder to S3
      - name: Deploy to S3
        run: |
          aws s3 sync client/dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete